indir = "../metadata/GLDS-1/"
outdir = "here/"
srcdir = "/Users/jonathanrubin/Google Drive/NASA/home/GeneLab-Microarray/GeneLab-Microarray"
tempdir = "/Users/jonathanrubin/Google Drive/NASA/home/GeneLab-Microarray/temp"
R_dir = "/Users/jonathanrubin/Google Drive/NASA/home/GeneLab-Microarray/R_scripts"
chip = "Auto"
batch = "False"
